// <auto-generated />
using System;
using Ardent.AuctionHouse.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ardent.AuctionHouse.Repository.Migrations
{
    [DbContext(typeof(AuctionHouseDbContext))]
    [Migration("20260728192120_SeedEvents")]
    partial class SeedEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ardent.AuctionHouse.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("Showings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca3d3541-cbda-4728-a923-454da8f4bd89"),
                            Date = new DateTime(2026, 7, 31, 19, 21, 19, 583, DateTimeKind.Utc).AddTicks(7393),
                            Location = "London",
                            Name = "Rare Watch Collection Auction",
                            Showings = "[]"
                        },
                        new
                        {
                            Id = new Guid("f107df23-f65d-4cbb-ab7b-20bb4276b57d"),
                            Date = new DateTime(2026, 8, 18, 19, 21, 19, 583, DateTimeKind.Utc).AddTicks(8426),
                            Location = "London",
                            Name = "Fine Art Auction",
                            Showings = "[]"
                        },
                        new
                        {
                            Id = new Guid("01dbc921-a06e-43cf-82d0-b1e6532f2a2c"),
                            Date = new DateTime(2026, 8, 4, 19, 21, 19, 583, DateTimeKind.Utc).AddTicks(8434),
                            Location = "Manchester",
                            Name = "Classic Car Auction",
                            Showings = "[]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
