// <auto-generated />
using System;
using Ardent.AuctionHouse.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ardent.AuctionHouse.Repository.Migrations
{
    [DbContext(typeof(AuctionHouseDbContext))]
    partial class AuctionHouseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ardent.AuctionHouse.Domain.Entities.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("character varying(350)");

                    b.Property<string>("Showings")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Date = new DateTime(2026, 7, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "London",
                            Name = "Rare Watch Collection Auction",
                            Showings = "[]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Date = new DateTime(2026, 8, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "London",
                            Name = "Fine Art Auction",
                            Showings = "[]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Date = new DateTime(2026, 8, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Location = "Manchester",
                            Name = "Classic Car Auction",
                            Showings = "[]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
